### PR TITLE
Added tests TestPrintProbeSuccess and TestPrintProbeFail

### LINKED ISSUE #232: Add tests for outputting information to stdout
## Summary

We have quite a handful of tests covering various aspects of the tool. However, one of the most crucial components of what tcping offers is not tested: 

- writing information to `STDOUT`

In the past, we have had PRs that unwantedly changed the way tcping displays information in the terminal.

We would like to have some tests to ensure the **intended fields** are displayed as per the provided flags by the user.

For instance, given the `-D` flag, the timestamp field should be present or in all cases, the `time` field (TTL in the code) should be there.

Any other tests improving the existing ones is also more than welcome

### PR DESCRIPTION
**Pull request by basil-gray**
## Describe your changes

Added two new tests to check the format and color of printProbeSuccess and printProbeFail

## Issue ticket number and link

Closes #232

### CODE REVIEW

**Comment by pouriyajamshidi** [comment]
Hi @basil-gray 

The tests are failing. Could you please have a look?

**Comment by basil-gray** [comment]
Hi @pouriyajamshidi 

I changed the tests to not account for colors. Could you run the workflow again?

**Comment by pouriyajamshidi** [comment]
Hi @basil-gray 

Thanks! the tests are passing now. Will have a close look and have this merged in. Appreciate your collaboration.

**Review by pouriyajamshidi — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
