### PR TITLE
Fix CI issue

### PR DESCRIPTION
**Pull request by SYSHIL**

### CODE REVIEW

**Comment by SYSHIL** [comment]
Hey @pouriyajamshidi I was expecting Codefactor to throw the same CI error I faced in https://github.com/pouriyajamshidi/tcping/pull/225 did something change?

**Comment by pouriyajamshidi** [comment]
Hey @SYSHIL 

No, nothing has changed code-base wise.

Although, I am not sure if empty commits cause the `codeFactor` to check the entire code or not. 

One surprising thing is that the CI is running without approval. In actual PRs, I have to always click `run` for the CI to trigger.

**Comment by pouriyajamshidi** [comment]
yep, I can confirm codeQL triggers on code changes! Best part is it does only check the parts you change and not the overall code-base :)

**Comment by SYSHIL** [comment]
Heyy @pouriyajamshidi sorry I missed this message from you, had a busy month...thanks for the knowledge share!

**Pull request closed without merging**
