### PR TITLE
Use github action to publish binary programs for all platforms.

### PR DESCRIPTION
**Pull request by vrichv**
## Describe your changes
Use github action to publish binary programs for all platforms.
Tested： https://github.com/vrichv/tcping/releases/tag/v1.12.1

## Issue ticket number and link
#35
Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added tests.
- [x] I have run `make check` and there are no failures.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by pouriyajamshidi** [comment]
Hi @vrichv and thanks for this fantastic job!

I have a few questions/requests:

1. unrelated to this PR, but out of curiosity, have you been able to test the Android executable? I don't have an Android but really curious if it works or not.
2. Could you please make sure that the outputs are conformant to the current structure? please check [this section](https://github.com/pouriyajamshidi/tcping#download-the-executables). There is no need to add all the releases to separate zip files. The most important thing is to make sure the current remain the same. Or if you think it does not really add any value, I am up to hear you out.
3. We also need to make sure this workflow runs only on push to the `Master` branch.

This PR addresses #35 and more.

Thanks again!

**Comment by vrichv** [comment]
>
1. Test on my android phone， failed to test with hostname.
```
d:\>adb push tcping-android-arm64-v8a /data/local/tmp/
tcping-android-arm64-v8a: 1 file pushed, 0 skipped. 101.2 MB/s (5701632 bytes in 0.054s)
d:\>adb shell
ANDROID:/ $ cd /data/local/tmp
ANDROID:/data/local/tmp $ chmod +x  tcping-android-arm64-v8a
ANDROID:/data/local/tmp $ ./tcping-android-arm64-v8a apple.com 443
Failed to resolve apple.com
1|ANDROID:/data/local/tmp $ ./tcping-android-arm64-v8a 17.253.144.10 443
TCPinging 17.253.144.10 on port 443
Reply from 17.253.144.10 on port 443 TCP_conn=1 time=13 ms
Reply from 17.253.144.10 on port 443 TCP_conn=2 time=35 ms
Reply from 17.253.144.10 on port 443 TCP_conn=3 time=12 ms
Reply from 17.253.144.10 on port 443 TCP_conn=4 time=14 ms
^C
--- 17.253.144.10 TCPing statistics ---
6 probes transmitted, 6 received, 0.00% packet loss
successful probes:   6
unsuccessful probes: 0
last successful probe:   2022-09-20 08:35:33
last unsuccessful probe: Never failed
total uptime:   6 seconds
total downtime: 0 second
longest consecutive uptime:   6 seconds from 2022-09-20 08:35:28 to 2022-09-20 08:35:33
rtt min/avg/max: 12/16.50/35 ms
--------------------------------------
TCPing started at: 2022-09-20 08:35:28
TCPing ended at:   2022-09-20 08:35:33
duration (HH:MM:SS): 00:00:05
```
I also tested linux-mips,linux-arm64 successfully.

2.I can add zip files if you decide to keep it compatible. However, I personally feel that adding multiple platforms leads to confusion with the old naming. Usually I use the following command to download: wget https://github.com/pouriyajamshidi/tcping/releases/latest/download/tcping_Linux.zip -O tcping.zip

**Comment by pouriyajamshidi** [comment]
> > 
> 
> 1. Test on my android phone， failed to test with hostname.
> 
> ```
> d:\>adb push tcping-android-arm64-v8a /data/local/tmp/
> tcping-android-arm64-v8a: 1 file pushed, 0 skipped. 101.2 MB/s (5701632 bytes in 0.054s)
> d:\>adb shell
> ANDROID:/ $ cd /data/local/tmp
> ANDROID:/data/local/tmp $ chmod +x  tcping-android-arm64-v8a
> ANDROID:/data/local/tmp $ ./tcping-android-arm64-v8a apple.com 443
> Failed to resolve apple.com
> 1|ANDROID:/data/local/tmp $ ./tcping-android-arm64-v8a 17.253.144.10 443
> TCPinging 17.253.144.10 on port 443
> Reply from 17.253.144.10 on port 443 TCP_conn=1 time=13 ms
> Reply from 17.253.144.10 on port 443 TCP_conn=2 time=35 ms
> Reply from 17.253.144.10 on port 443 TCP_conn=3 time=12 ms
> Reply from 17.253.144.10 on port 443 TCP_conn=4 time=14 ms
> ^C
> --- 17.253.144.10 TCPing statistics ---
> 6 probes transmitted, 6 received, 0.00% packet loss
> successful probes:   6
> unsuccessful probes: 0
> last successful probe:   2022-09-20 08:35:33
> last unsuccessful probe: Never failed
> total uptime:   6 seconds
> total downtime: 0 second
> longest consecutive uptime:   6 seconds from 2022-09-20 08:35:28 to 2022-09-20 08:35:33
> rtt min/avg/max: 12/16.50/35 ms
> --------------------------------------
> TCPing started at: 2022-09-20 08:35:28
> TCPing ended at:   2022-09-20 08:35:33
> duration (HH:MM:SS): 00:00:05
> ```
> 
> I also tested linux-mips,linux-arm64 successfully.
> 
> 2.I can add zip files if you decide to keep it compatible. However, I personally feel that adding multiple platforms leads to confusion with the old naming. Usually I use the following command to download:
> 
> ```
> https://github.com/pouriyajamshidi/tcping/releases/latest/download/tcping-linux-x64  -O tcping
> ```
> 
> 3.ok,delete section on pull_request.

1. Thanks for the confirmation.
2. I checked with a few users/companies that I know are using this tool and they would like to keep the formatting as is. It is integrated in their  CI pipelines and also I was made aware of some other projects that follow the same naming convention; zip folder indicates the platform and the executable in it, carries the project name. So, let's conform to the old style if it is not too much trouble for you.
3. Would you be addressing it yourself or you want me to do so?

**Comment by pouriyajamshidi** [comment]
Hey @vrichv ,

Are you willing to incorporate the requested changes? 
This is a good addition to this project and I want it to go in with your name.

Thanks in advance

**Comment by pouriyajamshidi** [comment]
Hey @ChrisClarke246,

Neither do I 😄. The logic seems fine. We will test it whenever we get our hands on such machine.

Thanks

**Pull request closed without merging**
