### PR TITLE
Add better gifs using VHS

### LINKED ISSUE #66: Update demo GIFs in the README
## Summary

The program has evolved and the output display has changed quite a bit. Yet, the demo GIFs in the README are demonstrating the old version of TCPING.

We need new GIFs show casing the new output similar to the current ones.

### PR DESCRIPTION
**Pull request by ravsii**
## Describe your changes

Add better gifs, using [VHS](https://github.com/charmbracelet/vhs) (neat tool tbh). There were 2 gifs in the readme (but 4 in /Images), I only updated the ones that are present in README.md. Old files are still there for the time being.

Also `make gifs` was added to quickly rebuild gifs if needed.

If you'd like me to change anything or add more gifs, I'm open to discuss

tcping:
tcping

tcping with flag
tcping_resolve

## Issue ticket number and link

Closes #66 

## Type of change

- [x] This change requires a documentation update

### CODE REVIEW

**Comment by pouriyajamshidi** [comment]
Hi @ravsii,

Thanks a lot for your PR and introducing the VHS tool. Never heard of it but it looks very cool! 👍🏻 

Would it be too much to ask you to have "example.com" as the destination?

There's a potential for some legal issues. We had some problems in the past.

**Comment by ravsii** [comment]
Thanks for the review @pouriyajamshidi 

> Would it be too much to ask you to have "example.com" as the destination?

Sure

> Also wondering why the retry resolve did not trigger after the third failure 🤔. Seems like a bug but I could not reproduce.

I guess it's not a bug. VHS records output for a certain amount of time, 5 seconds in my case (you can see that in .tape files). I guess I just need to play with the timer.

> **PS**: You might need to rebase your branch. I had another branch merged in but it does not really conflict with yours.

No worries

**Comment by ravsii** [comment]
Seems like `-r` is actually broken for me. Do you want to create an issue? For gifs I just made it `^c` at the right time, although I believe that's not how it should be.

Updated versions. 
tcping
tcping_resolve

**Comment by pouriyajamshidi** [comment]
Hi @ravsii,

Thanks a lot for the prompt response and the amazing work. Looks very professional.

> Edit: actually, it could be a bug. I've run tcping example.com 81 -r 3 and it did retry 31 times and still going. I'll create an issue later (if I'll be able to reproduce)

> Seems like `-r` is actually broken for me. Do you want to create an issue? For gifs I just made it `^c` at the right time, although I believe that's not how it should be.

Please feel free to create an issue. I will try to also have another go tomorrow to see if I can reproduce. So far, I tested on Windows and Linux machines and it looks ok. Are you using a Mac?

By the way, which version of tcping are you using?

```bash
tcping -v
```

In the meantime, let's merge this. 🚀

**Review by pouriyajamshidi — APPROVED** [review]
Perfect.

**Pull request merged**
