### PR TITLE
add custom timeout between to packets functionality

### LINKED ISSUE #7: Custom timeout values
## Summary

Currently `tcping` is having a hard-coded timeout value of 1 second. Being able to change this value through a flag can be useful for some scenarios but requires a major refactoring.

### PR DESCRIPTION
**Pull request by luca-patrignani**
# Important

**Please provide the requested parameters below to help us review your pull request.**

**Pull requests without a body or explanation will be rejected.**

## Describe your changes
I implemented the functionality for custon timeout values 
## Issue ticket number and link
#7 
Closes #7 
## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added tests.
- [ ] I have run `make check` and there are no failures.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

This is my very first PR so forgive me I made some silly mistakes.

### CODE REVIEW

**Comment by pouriyajamshidi** [comment]
Hi @luca-patrignani,

Thanks a lot for your contribution.

At the first glance it looks good. Please give me some time to review this.

**Review by pouriyajamshidi — CHANGES_REQUESTED** [review]
Hi @luca-patrignani,

I had a closer look at your PR and it is in fact a nice feature you have implemented and could be quite handy for some users. However, it is not what the issue is requesting to be deployed.

The issue is asking for an optional `net.DialTimeout` value here https://github.com/pouriyajamshidi/tcping/blob/d9d00f626d0695ee3a1daa98965e9da1109a35bc/tcping.go#L640

which also means the `ticker` has also change here https://github.com/pouriyajamshidi/tcping/blob/d9d00f626d0695ee3a1daa98965e9da1109a35bc/tcping.go#L656


If you are still willing to continue the work on #7 , I suggest discarding all the changes so far and address the aforementioned points and use `-t` as the flag.

Sorry if the issue was not detailed enough to lead to this confusion.

**Comment by luca-patrignani** [comment]
Hi,
I'm sorry for the inconvinience, I was misled by #111 which mentioned the #7 issue. I'm closing this PR and I'll create a new one when I implement the `-t` feature.

**Comment by luca-patrignani** [comment]
I need help understanding how and why the `ticker` has to change. 
I don't think this is the proper place to ask this question, if there is a better place let me know.

**Comment by pouriyajamshidi** [comment]
Hi @luca-patrignani,

Thanks again for your contribution! yea the #111 was a bit misleading

> I need help understanding how and why the `ticker` has to change. I don't think this is the proper place to ask this question, if there is a better place let me know.

right, I was thinking if someone sets the timeout to say 3 seconds and we tick at a second, this could cause some odd behavior. If it is not needed to change then, it is fine.

**Comment by luca-patrignani** [comment]
Hi @pouriyajamshidi,
At this moment github doesn't allow me to reopen the PR so tomorrow I'm starting working on it, or open a fresh new PR.

**Pull request closed without merging**
