### PR TITLE
add Dockerfile

### PR DESCRIPTION
**Pull request by SergeyParamoshkin**
used scratch
size image 5.19MB

### CODE REVIEW

**Review by pouriyajamshidi — CHANGES_REQUESTED** [review]

**Comment by pouriyajamshidi** [comment]
when I build the image and run:

```bash
docker run --rm tcping:develop example.com 443
```

I get:

```console
exec /usr/bin/tcping: no such file or directory
```

Any ideas why that could be?

By the way, if you use the latest commits, the `go build` command also requires the `statsprinter.go` file. But I don't think it is really relevant here.

**Comment by SergeyParamoshkin** [comment]
> when I build the image and run:
> 
> ```shell
> docker run --rm tcping:develop example.com 443
> ```
> 
> I get:
> 
> ```
> exec /usr/bin/tcping: no such file or directory
> ```
> 
> Any ideas why that could be?
> 
> By the way, if you use the latest commits, the `go build` command also requires the `statsprinter.go` file. But I don't think it is really relevant here.
> 
> I inspected the container's filesystem and `tcping` appears to be there. Not sure what else is going on. P.S. I am building it on an Ubuntu machine

fix

**Comment by pouriyajamshidi** [comment]
> > when I build the image and run:
> > ```shell
> > docker run --rm tcping:develop example.com 443
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I get:
> > ```
> > exec /usr/bin/tcping: no such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any ideas why that could be?
> > By the way, if you use the latest commits, the `go build` command also requires the `statsprinter.go` file. But I don't think it is really relevant here.
> > I inspected the container's filesystem and `tcping` appears to be there. Not sure what else is going on. P.S. I am building it on an Ubuntu machine
> 
> fix

Nice job! 🚀

**Comment by pouriyajamshidi** [comment]
by the way, are you building the container on a Windows machine?

**Comment by SergeyParamoshkin** [comment]
> by the way, are you building the container on a Windows machine?

oh, no. I try install vm with windows and try run.

**Comment by pouriyajamshidi** [comment]
> > by the way, are you building the container on a Windows machine?
> 
> oh, no. I try install vm with windows and try run.

No need to install a Windows machine. I am also on a Linux machine but not sure why the build does not work on my end :S

I keep scratching my head but the issue is not apparent to me. Maybe give it a go on the latest commit on master and see?

**Comment by SergeyParamoshkin** [comment]
> > > by the way, are you building the container on a Windows machine?
> > 
> > 
> > oh, no. I try install vm with windows and try run.
> 
> No need to install a Windows machine. I am also on a Linux machine but not sure why the build does not work on my end :S
> 
> I keep scratching my head but the issue is not apparent to me. Maybe give it a go on the latest commit on master and see?

push on master this repo ?

**Pull request closed without merging**
